"""add worldactormeta table

游戏世界（Agent 进化与实战区域）的成员展示元数据表：皮肤等纯表现层属性，
独立于 AssistantAIConfig 主表（见 doc/Agent进化与实战区域设计方案.md §7.4）。

Revision ID: 32c720138db6
Revises: f31c1a96d4e7
Create Date: 2026-06-11 06:47:18.481321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (AutoString, ...) used in autogenerated ops


# revision identifiers, used by Alembic.
revision: str = '32c720138db6'
down_revision: Union[str, Sequence[str], None] = 'f31c1a96d4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('worldactormeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=False),
    sa.Column('skin_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worldactormeta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worldactormeta_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worldactormeta_user_id'), ['user_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('worldactormeta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worldactormeta_user_id'))
        batch_op.drop_index(batch_op.f('ix_worldactormeta_ai_config_id'))

    op.drop_table('worldactormeta')
