"""baseline schema

Revision ID: a749d4b02c72
Revises: 
Create Date: 2026-06-09 11:33:46.825436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (AutoString, ...) used in autogenerated ops


# revision identifiers, used by Alembic.
revision: str = 'a749d4b02c72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adminauditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adminauditlog_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_adminauditlog_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adminauditlog_created_at'), ['created_at'], unique=False)

    op.create_table('agentdispatchtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agentdispatchtask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agentdispatchtask_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentdispatchtask_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentdispatchtask_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentdispatchtask_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_agentdispatchtask_user_id'), ['user_id'], unique=False)

    op.create_table('endpointagentpresence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capabilities_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_defs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpointagentpresence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpointagentpresence_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpointagentpresence_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpointagentpresence_online'), ['online'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpointagentpresence_user_id'), ['user_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('admin_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mcp_max_steps', sa.Integer(), nullable=False),
    sa.Column('role_mcp_permissions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tavily_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_presets', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_supervision_idle_seconds', sa.Integer(), nullable=False),
    sa.Column('ai_message_inquiry_reminder_seconds', sa.Integer(), nullable=False),
    sa.Column('ui_theme_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_font_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_brain_view_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_plain_text_output_enabled', sa.Boolean(), nullable=False),
    sa.Column('ui_thinking_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_mcp_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_mcp_success_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_mcp_error_icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_thinking_icon_enabled', sa.Boolean(), nullable=False),
    sa.Column('ui_mcp_success_icon_enabled', sa.Boolean(), nullable=False),
    sa.Column('ui_mcp_error_icon_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account'), ['account'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('agenttypemcppermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tools_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agenttypemcppermission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenttypemcppermission_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenttypemcppermission_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenttypemcppermission_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenttypemcppermission_user_id'), ['user_id'], unique=False)

    op.create_table('airuntimestatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('mcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_mcp_tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airuntimestatus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airuntimestatus_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_airuntimestatus_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_airuntimestatus_user_id'), ['user_id'], unique=False)

    op.create_table('assistantaiconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_preset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strip_markdown_symbols', sa.Boolean(), nullable=False),
    sa.Column('ai_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('digital_member_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_librarian', sa.Boolean(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('token_limit', sa.Integer(), nullable=False),
    sa.Column('lifecycle_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_behavior', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_root', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('database_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bot_channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bot_configs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_ai_config_id', sa.Integer(), nullable=True),
    sa.Column('root_manager_ai_config_id', sa.Integer(), nullable=True),
    sa.Column('management_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('switch_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mcp_tools', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_auto_control', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assistantaiconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_ai_role'), ['ai_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_bot_channel'), ['bot_channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_is_librarian'), ['is_librarian'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_model_preset_id'), ['model_preset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_parent_ai_config_id'), ['parent_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_root_manager_ai_config_id'), ['root_manager_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistantaiconfig_user_id'), ['user_id'], unique=False)

    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('think', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finish_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessage_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessage_user_id'), ['user_id'], unique=False)

    op.create_table('chatrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.Column('heartbeat_at', sa.Float(), nullable=True),
    sa.Column('worker_kwargs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatrun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatrun_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatrun_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatrun_run_id'), ['run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chatrun_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatrun_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatrun_user_id'), ['user_id'], unique=False)

    op.create_table('chatsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatsession_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatsession_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatsession_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatsession_user_id'), ['user_id'], unique=False)

    op.create_table('evolutioninput',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evolution_input_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_ai_config_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolutioninput', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolutioninput_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolutioninput_evolution_input_id'), ['evolution_input_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_evolutioninput_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolutioninput_source_ai_config_id'), ['source_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolutioninput_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolutioninput_user_id'), ['user_id'], unique=False)

    op.create_table('evolutionproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_member_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolutionproject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolutionproject_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolutionproject_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolutionproject_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolutionproject_user_id'), ['user_id'], unique=False)

    op.create_table('knowledgeentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_target', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=True),
    sa.Column('source_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_generation', sa.Integer(), nullable=True),
    sa.Column('source_ai_config_id', sa.Integer(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('librarian_ai_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledgeentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledgeentry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledgeentry_librarian_ai_config_id'), ['librarian_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledgeentry_memory_id'), ['memory_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledgeentry_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledgeentry_source_ai_config_id'), ['source_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledgeentry_source_job_id'), ['source_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledgeentry_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledgeentry_user_id'), ['user_id'], unique=False)

    op.create_table('memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_memory_id'), ['memory_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_memory_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_user_id'), ['user_id'], unique=False)

    op.create_table('tokenusagesnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokenusagesnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokenusagesnapshot_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokenusagesnapshot_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokenusagesnapshot_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokenusagesnapshot_user_id'), ['user_id'], unique=False)

    op.create_table('agentaibinding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ai_config_id'], ['assistantaiconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agentaibinding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agentaibinding_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentaibinding_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agentaibinding_user_id'), ['user_id'], unique=False)

    op.create_table('aimessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_ai_config_id', sa.Integer(), nullable=False),
    sa.Column('to_ai_config_id', sa.Integer(), nullable=False),
    sa.Column('target_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reply_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('require_reply', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cascade_depth', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.Float(), nullable=True),
    sa.Column('reply_reminded_at', sa.Float(), nullable=True),
    sa.Column('replied_at', sa.Float(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_ai_config_id'], ['assistantaiconfig.id'], ),
    sa.ForeignKeyConstraint(['to_ai_config_id'], ['assistantaiconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aimessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aimessage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aimessage_from_ai_config_id'), ['from_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aimessage_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aimessage_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_aimessage_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_aimessage_target_session_id'), ['target_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aimessage_to_ai_config_id'), ['to_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aimessage_user_id'), ['user_id'], unique=False)

    op.create_table('aitaskjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=False),
    sa.Column('created_by_ai_config_id', sa.Integer(), nullable=True),
    sa.Column('created_by_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completion_notified_at', sa.Float(), nullable=True),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_supervised_at', sa.Float(), nullable=True),
    sa.Column('supervision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ai_config_id'], ['assistantaiconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aitaskjob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aitaskjob_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_created_by_ai_config_id'), ['created_by_ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_created_by_session_id'), ['created_by_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_aitaskjob_last_run_id'), ['last_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_trigger_type'), ['trigger_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_aitaskjob_user_id'), ['user_id'], unique=False)

    op.create_table('botsessionroute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=False),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_msg_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ai_config_id'], ['assistantaiconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('botsessionroute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_botsessionroute_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_botsessionroute_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_botsessionroute_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_botsessionroute_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_botsessionroute_user_id'), ['user_id'], unique=False)

    op.create_table('botusercursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=False),
    sa.Column('ai_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identity_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ai_config_id'], ['assistantaiconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('botusercursor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_botusercursor_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_botusercursor_ai_kind'), ['ai_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_botusercursor_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_botusercursor_identity_key'), ['identity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_botusercursor_user_id'), ['user_id'], unique=False)

    op.create_table('chatmessagemedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chatmessage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatmessagemedia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatmessagemedia_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessagemedia_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatmessagemedia_user_id'), ['user_id'], unique=False)

    op.create_table('valhallaentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ai_config_id', sa.Integer(), nullable=False),
    sa.Column('ai_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unfinished_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artifacts_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_report_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_used', sa.Integer(), nullable=False),
    sa.Column('token_limit', sa.Integer(), nullable=False),
    sa.Column('artifacts_count', sa.Integer(), nullable=False),
    sa.Column('unfinished_count', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ai_config_id'], ['assistantaiconfig.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valhallaentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valhallaentry_ai_config_id'), ['ai_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valhallaentry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_valhallaentry_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valhallaentry_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_valhallaentry_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valhallaentry_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valhallaentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valhallaentry_user_id'))
        batch_op.drop_index(batch_op.f('ix_valhallaentry_session_id'))
        batch_op.drop_index(batch_op.f('ix_valhallaentry_kind'))
        batch_op.drop_index(batch_op.f('ix_valhallaentry_job_id'))
        batch_op.drop_index(batch_op.f('ix_valhallaentry_created_at'))
        batch_op.drop_index(batch_op.f('ix_valhallaentry_ai_config_id'))

    op.drop_table('valhallaentry')
    with op.batch_alter_table('chatmessagemedia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessagemedia_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatmessagemedia_token'))
        batch_op.drop_index(batch_op.f('ix_chatmessagemedia_message_id'))

    op.drop_table('chatmessagemedia')
    with op.batch_alter_table('botusercursor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_botusercursor_user_id'))
        batch_op.drop_index(batch_op.f('ix_botusercursor_identity_key'))
        batch_op.drop_index(batch_op.f('ix_botusercursor_channel'))
        batch_op.drop_index(batch_op.f('ix_botusercursor_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_botusercursor_ai_config_id'))

    op.drop_table('botusercursor')
    with op.batch_alter_table('botsessionroute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_botsessionroute_user_id'))
        batch_op.drop_index(batch_op.f('ix_botsessionroute_session_id'))
        batch_op.drop_index(batch_op.f('ix_botsessionroute_channel'))
        batch_op.drop_index(batch_op.f('ix_botsessionroute_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_botsessionroute_ai_config_id'))

    op.drop_table('botsessionroute')
    with op.batch_alter_table('aitaskjob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aitaskjob_user_id'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_template_id'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_status'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_session_id'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_priority'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_last_run_id'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_job_id'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_created_by_session_id'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_created_by_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_created_at'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_aitaskjob_ai_config_id'))

    op.drop_table('aitaskjob')
    with op.batch_alter_table('aimessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aimessage_user_id'))
        batch_op.drop_index(batch_op.f('ix_aimessage_to_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_aimessage_target_session_id'))
        batch_op.drop_index(batch_op.f('ix_aimessage_status'))
        batch_op.drop_index(batch_op.f('ix_aimessage_message_type'))
        batch_op.drop_index(batch_op.f('ix_aimessage_message_id'))
        batch_op.drop_index(batch_op.f('ix_aimessage_from_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_aimessage_created_at'))

    op.drop_table('aimessage')
    with op.batch_alter_table('agentaibinding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agentaibinding_user_id'))
        batch_op.drop_index(batch_op.f('ix_agentaibinding_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_agentaibinding_agent_id'))

    op.drop_table('agentaibinding')
    with op.batch_alter_table('tokenusagesnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenusagesnapshot_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokenusagesnapshot_bucket'))
        batch_op.drop_index(batch_op.f('ix_tokenusagesnapshot_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_tokenusagesnapshot_ai_config_id'))

    op.drop_table('tokenusagesnapshot')
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_user_id'))
        batch_op.drop_index(batch_op.f('ix_memory_project_id'))
        batch_op.drop_index(batch_op.f('ix_memory_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_kind'))
        batch_op.drop_index(batch_op.f('ix_memory_job_id'))
        batch_op.drop_index(batch_op.f('ix_memory_created_at'))
        batch_op.drop_index(batch_op.f('ix_memory_archived'))
        batch_op.drop_index(batch_op.f('ix_memory_ai_config_id'))

    op.drop_table('memory')
    with op.batch_alter_table('knowledgeentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_status'))
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_source_job_id'))
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_source_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_scope'))
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_memory_id'))
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_librarian_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_knowledgeentry_created_at'))

    op.drop_table('knowledgeentry')
    with op.batch_alter_table('evolutionproject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolutionproject_user_id'))
        batch_op.drop_index(batch_op.f('ix_evolutionproject_status'))
        batch_op.drop_index(batch_op.f('ix_evolutionproject_project_id'))
        batch_op.drop_index(batch_op.f('ix_evolutionproject_name'))

    op.drop_table('evolutionproject')
    with op.batch_alter_table('evolutioninput', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolutioninput_user_id'))
        batch_op.drop_index(batch_op.f('ix_evolutioninput_type'))
        batch_op.drop_index(batch_op.f('ix_evolutioninput_source_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_evolutioninput_review_status'))
        batch_op.drop_index(batch_op.f('ix_evolutioninput_evolution_input_id'))
        batch_op.drop_index(batch_op.f('ix_evolutioninput_created_at'))

    op.drop_table('evolutioninput')
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatsession_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatsession_session_id'))
        batch_op.drop_index(batch_op.f('ix_chatsession_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_chatsession_ai_config_id'))

    op.drop_table('chatsession')
    with op.batch_alter_table('chatrun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatrun_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatrun_status'))
        batch_op.drop_index(batch_op.f('ix_chatrun_session_id'))
        batch_op.drop_index(batch_op.f('ix_chatrun_run_id'))
        batch_op.drop_index(batch_op.f('ix_chatrun_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_chatrun_ai_config_id'))

    op.drop_table('chatrun')
    with op.batch_alter_table('chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatmessage_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_session_id'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_chatmessage_ai_config_id'))

    op.drop_table('chatmessage')
    with op.batch_alter_table('assistantaiconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_user_id'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_root_manager_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_project_id'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_parent_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_name'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_model_preset_id'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_is_librarian'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_bot_channel'))
        batch_op.drop_index(batch_op.f('ix_assistantaiconfig_ai_role'))

    op.drop_table('assistantaiconfig')
    with op.batch_alter_table('airuntimestatus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airuntimestatus_user_id'))
        batch_op.drop_index(batch_op.f('ix_airuntimestatus_ai_kind'))
        batch_op.drop_index(batch_op.f('ix_airuntimestatus_ai_config_id'))

    op.drop_table('airuntimestatus')
    with op.batch_alter_table('agenttypemcppermission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenttypemcppermission_user_id'))
        batch_op.drop_index(batch_op.f('ix_agenttypemcppermission_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_agenttypemcppermission_agent_type'))
        batch_op.drop_index(batch_op.f('ix_agenttypemcppermission_agent_id'))

    op.drop_table('agenttypemcppermission')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_account'))

    op.drop_table('user')
    with op.batch_alter_table('endpointagentpresence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpointagentpresence_user_id'))
        batch_op.drop_index(batch_op.f('ix_endpointagentpresence_online'))
        batch_op.drop_index(batch_op.f('ix_endpointagentpresence_ai_config_id'))
        batch_op.drop_index(batch_op.f('ix_endpointagentpresence_agent_id'))

    op.drop_table('endpointagentpresence')
    with op.batch_alter_table('agentdispatchtask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agentdispatchtask_user_id'))
        batch_op.drop_index(batch_op.f('ix_agentdispatchtask_task_id'))
        batch_op.drop_index(batch_op.f('ix_agentdispatchtask_status'))
        batch_op.drop_index(batch_op.f('ix_agentdispatchtask_created_at'))
        batch_op.drop_index(batch_op.f('ix_agentdispatchtask_ai_config_id'))

    op.drop_table('agentdispatchtask')
    with op.batch_alter_table('adminauditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adminauditlog_created_at'))
        batch_op.drop_index(batch_op.f('ix_adminauditlog_actor_id'))
        batch_op.drop_index(batch_op.f('ix_adminauditlog_action'))

    op.drop_table('adminauditlog')
    # ### end Alembic commands ###
